apiVersion: v1
data:
  # echo -n 'mongodb://root:password@mongo:27017' | base64
  QUARKUS_MONGODB_CONNECTION_STRING: bW9uZ29kYjovL3Jvb3Q6cGFzc3dvcmRAbW9uZ286MjcwMTc=
kind: Secret
metadata:
  name: api-mongo-secrets
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: api-mongo
  labels:
    app: feedsaggregator
    tier: api-mongo
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: feedsaggregator
    tier: api-mongo
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: api-mongo
spec:
  selector:
    matchLabels:
      app: feedsaggregator
      tier: api-mongo
  replicas: 2
  template:
    metadata:
      labels:
        app: feedsaggregator
        tier: api-mongo
    spec:
      containers:
        - name: api-mongo
          image: example.com/feedsaggregator/api-mongo
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: api-mongo-secrets
                  key: QUARKUS_MONGODB_CONNECTION_STRING
          ports:
            - containerPort: 8080