# Configuration for `process-all-feeds.xml` job.
# Structure:
# - group1:
#   - code: feedcode1
#     url: feedurl1
#   - code: feedcode2
#     url: feedurl2
# - group2:
#   - code: feedcode3
#     url: feedurl3
#   - code: feedcode4
#     url: feedurl4

- aerogear:
    - code: aerogear
      url: http://corinnekrych.blogspot.com/feeds/posts/default?alt=rss
- quarkus:
    - code: quarkus
      url: https://quarkus.io/feed.xml
- keycloak:
    - code: keycloak
      url: https://www.keycloak.org/rss.xml
- nonmiddelware:
    - code: redhat_developer_blog
      url: https://developers.redhat.com/blog/feed/