apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: feedsagg-build-pipeline
spec:
  params:
    - name: gitUrl
      type: string
      description: The git repository URL to clone from.
      default: 'https://github.com/jbossorg/feedsaggregator.git'
    - name: gitRevision
      type: string
      description: The git branch to clone.
      default: 'main'
    - name: imageRegistry
      type: string
      description: Registry url
    - name: insecureRegistry
      type: string
      description: Allow insecure registry
    - name: imageGroup
      type: string
      description: Container image group
      default: 'feedsaggregator'
    - name: imageTag
      type: string
      description: Container image tag (Default is project version)
    - name: baseImage
      type: string
      description: base image to run maven build and output image build
      default: 'registry.access.redhat.com/ubi8/openjdk-11'
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.gitUrl)
        - name: revision
          value: $(params.gitRevision)
        - name: deleteExisting
          value: "true"
    - name: build-push-image
      taskRef:
        name: maven
      runAfter:
        - fetch-repository
      params:
        - name: GOALS
          value:
            - -DskipTests
            - -Dbuild.jib.base-jvm-image=$(params.baseImage)
            - -Dbuild.container-image.group=$(params.imageGroup)
            - -Dbuild.container-image.name-prefix=
            - -Dbuild.container-image.tag=$(params.imageTag)
            - -Djib.allowInsecureRegistries=$(params.insecureRegistry)
            - -Dbuild.container-image.registry=$(params.imageRegistry)
            - -Dcontainer-deploy
            - clean
            - package
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace