# This workflow will build a package using Maven and then publish it to dockerhub packages when a release is created

name: Deploy to Docker Hub

on:
  push:
    tags:
      - '*'

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build with Maven
      run: mvn -B -Dcontainer-deploy -Dbuild.container-image.registry=docker.io -Dbuild.container-image.group=jbossorg -Djib.allowInsecureRegistries=false package --file pom.xml
